### ISSUE TITLE
feature request: use obfs4proxy from the -backports (under Debian)

### ISSUE THREAD

**Issue by toralf** [NewNewYorkBridges/ansible-tor-bridge#20]
There was a recent discussion at the Tor relay mailing list to run the latest obfs4proxy.. At least for Debian (bullseye) this is advised:

```
Yes, first edit '/etc/apt/sources.list':

# bullseye-backports, previously on backports.debian.org
deb http://deb.debian.org/debian/ bullseye-backports main
#deb-src http://deb.debian.org/debian/ bullseye-backports main

Then install:

apt update
apt install -t bullseye-backports obfs4proxy
```
which needs slightly adaption to the current ansible code.

**Comment by toralf** [comment]
So something like 
```
- name: obfs4proxy installation
  ansible.builtin.apt:
    name: "obfs4proxy"
    default_release: "bullseye-backports"
    update_cache: yes
    state: latest
```
is needed to close the security gap which is in the stable Debian package.
